services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./shared/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    entrypoint: sh -c "wget --no-check-certificate -O /etc/prometheus/prometheus-local.yml https://raw.githubusercontent.com/DannaAEspinosa/grafana-stack/main/prometheus/prometheus.yml && exec /bin/prometheus --config.file=/etc/prometheus/prometheus-local.yml --web.enable-remote-write-receiver"
    networks:
      - grafana-network #Asegurar que estén en la misma red todos los servicios

  loki:
    image: grafana/loki:latest
    container_name: loki
    command:
      - "-config.file=/etc/loki/local-config.yaml"  
    volumes:
      - ./shared/loki/chunks:/loki/chunks/
      - ./shared/loki/rules:/loki/rules/
    ports:
      - "3100:3100"
    networks:
      - grafana-network #Asegurar que estén en la misma red todos los servicios

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command:
      - "-config.file=/etc/promtail/config.yml"   
      - ./shared/logs:/var/log   
    depends_on:
      - loki
    networks:
      - grafana-network #Asegurar que estén en la misma red todos los servicios   

  alloy:
    image: grafana/alloy:latest  
    container_name: alloy
    command:
      - "-config.file=/etc/alloy/config.alloy"  
    volumes:
      - ./shared/alloy:/etc/alloy
    ports:
      - "4317:4317"  
      - "4318:4318"  
    entrypoint: sh -c "apt-get update -y && apt-get -y install wget && wget --no-check-certificate -O /etc/alloy/config.alloy https://raw.githubusercontent.com/DannaAEspinosa/grafana-stack/main/alloy/config.alloy && exec /bin/alloy run /etc/alloy/config.alloy"
    networks:
      - grafana-network #Asegurar que estén en la misma red todos los servicios

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./shared/grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false #No credenciales
    ports:
      - "3000:3000"
    entrypoint: sh -c "wget --no-check-certificate -O /etc/grafana/provisioning/datasources/datasources.yml https://raw.githubusercontent.com/DannaAEspinosa/grafana-stack/main/grafana/datasources.yml && exec sh /run.sh"

  dreamy_allen:
    image: outcome
    container_name: outcurr
    ports:
      - "8083:8083"
    networks:
      - grafana-network

volumes:
  prometheus-data:
  

networks:
  grafana-network:
    external: true
